apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.name }}
  labels:
    name: {{ .Values.name }}
spec:
  type: {{ .Values.service.type }}
  ports: # 多端口
    {{- range $key, $val := .Values.service.ports }}
    - port: {{ $val }}
      name: {{ $val | quote}}
      targetPort: {{ $val }}
      protocol: TCP
    {{- end }}
  selector:
    app: {{ .Values.name }}
